### ISSUE TITLE
我是唯一的那一个特例吗...一直不能登录帐号

### ISSUE THREAD

**Issue by shoaly** [greatyao/v2ex-android#10]
![image](https://cloud.githubusercontent.com/assets/2660914/18674700/b9423eea-7f82-11e6-800f-8069ca88cfd3.png)

以上是截图

**Comment by greatyao** [comment]
没法登陆吗？确定你用的是2.8.0以上版本吗？

**Comment by shoaly** [comment]
我从 realease中 下载的 最近的apk.. 前一个版本也是无法登陆的

_---------------------------------------------------------------------------------_

**Comment by greatyao** [comment]
从google play市场上下载最新的吧 
前几个月v2ex网站更改了登录代码，2.8.0以上版本修复了登录问题

**Comment by shoaly** [comment]
没装 google play, 莫非 github上 release 还不是最新的吗....原来入资

_---------------------------------------------------------------------------------_

**Comment by shoaly** [comment]
原来如此

_---------------------------------------------------------------------------------_

2016-09-21 14:00 GMT+08:00 xiao xuli shoalyxiao@gmail.com:

**Comment by greatyao** [comment]
github下载的有自动更新/新版检测功能的，直接下载替换就是了

**Comment by shoaly** [comment]
恩 , 已经解决

_---------------------------------------------------------------------------------_
