### ISSUE TITLE
关于应用开发的一点疑问

### ISSUE THREAD

**Issue by fan123199** [greatyao/v2ex-android#5]
V友好
本来是想看这个app的源码学习一下android的工程，发现完全动不下去，太复杂了。作为Android菜鸟，有些疑问。
1，看了代码，发现架构完善，类非常多，相比其他的V2ex android客户端复杂很多，都是你一个人的工作吗？
2，如果是的话，需要大概多久的工作量？
3，我需要补充哪些知识或基础来更快的理解这个项目？
谢谢

**Comment by greatyao** [comment]
需要了解的知道包括但不局限于：
1.数据库以及持久化
2.网络通信尤其是http数据的请求与接受
3.ListView和Adapter的关联
4.Fragment和Activity
5.等等

相关方面的记录在博客里有记录
