### ISSUE TITLE
请问是被 Play 下架了么还是项目弃坑掉了？链接已经失效。

### ISSUE THREAD

**Issue by awkj** [greatyao/v2ex-android#9]

**Comment by greatyao** [comment]
由于用了友盟的更新SDK被google下架 还没来得及重新上架

**Comment by awkj** [comment]
我使用了旧的版本登陆后，自动推送了新版 2.8，这应该是最新版了吧？

**Comment by greatyao** [comment]
嗯 最新版是2.8.1 过段时间准备重新上架

**Comment by greatyao** [comment]
现在已经在play重新上架

**Comment by awkj** [comment]
已get！

**Comment by awkj** [comment]
更换了包名么？我发现评价全部丢失了。

**Comment by greatyao** [comment]
嗯，原来的应用被google给暂停了，申诉了也没用，只能换个包名。

**Comment by awkj** [comment]
可以去 V2 广而告之一下，之前蛮多人都用你这个app的，只是后来神秘消失后，就转 V2EX+ 了。
